---
- name: Update gravity
  ansible.builtin.command:
    cmd: pihole -g &
  changed_when: true

- name: Restart samba-ad-dc
  ansible.builtin.systemd_service:
    name: samba-ad-dc
    state: restarted

- name: Restart pihole-FTL
  ansible.builtin.systemd_service:
    name: pihole-FTL
    state: restarted
